//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hw_104_WPF_Northwind_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spartan
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string University { get; set; }
        public string Course { get; set; }
        public string Degree_Classification { get; set; }
    }
}
